import React, { useState, useEffect } from 'react';
import { ChantInput } from '../ui/inputs/ChantInput';
import { ModernScore } from '../ui/scores/modern/ModernScore';
import { GregorianScore } from '../ui/scores/gregorian/GregorianScore';
import { Controls } from './Controls';
import { AnalysisPanel } from './AnalysisPanel';
import { exportJSON, exportMIDI } from './ExportUtils';

// Logic Imports
import { generateOrganum } from '../engine/Generator';
import { STYLES } from '../core/rules/StyleDefinitions';
import { mapToNeumes } from '../ui/scores/gregorian/NeumeMapper';
import { playScore, stopPlayback } from '../audio/AudioEngine';

export const App = () => {
  // --- State ---
  const [chant, setChant] = useState([]);
  const [organum, setOrganum] = useState([]);
  const [style, setStyle] = useState(STYLES.MICROLOGUS);
  const [playbackIndex, setPlaybackIndex] = useState(-1);
  const [isPlaying, setIsPlaying] = useState(false);
  const [error, setError] = useState(null);

  // --- Handlers ---

  const handleChantChange = (newChant) => {
    setChant(newChant);
    setOrganum([]); // Clear old generation
    setError(null);
    stopPlayback();
    setIsPlaying(false);
    setPlaybackIndex(-1);
  };

  const handleGenerate = () => {
    if (chant.length === 0) return;

    // Auto-detect mode final from last note of chant
    const lastNote = chant[chant.length - 1];
    const modeFinal = lastNote.step; // 'D', 'E', 'F', 'G'

    const result = generateOrganum(chant, style, modeFinal);

    if (result.success) {
      setOrganum(result.organumVoice);
      setError(null);
    } else {
      setOrganum([]);
      setError(result.error);
    }
  };

  const handlePlay = () => {
    if (chant.length === 0) return;
    setIsPlaying(true);
    setError(null);

    // Prepare Data
    // We map to Neumes here to ensure audio engine gets the structured data
    const chantNeumes = mapToNeumes(chant);
    const organumNeumes = organum.length > 0 ? mapToNeumes(organum) : [];

    playScore(
      { chantNeumes, organumNeumes },
      100, // BPM
      (index) => setPlaybackIndex(index), // On Tick
      () => {
        setIsPlaying(false); 
        setPlaybackIndex(-1);
      } // On Complete
    );
  };

  const handleStop = () => {
    stopPlayback();
    setIsPlaying(false);
    setPlaybackIndex(-1);
  };

  const handleExport = () => {
    exportMIDI(chant, organum);
    exportJSON(chant, organum, style, { exportedBy: 'MedievalGen v1' });
  };

  const handleClear = () => {
    handleStop();
    setChant([]);
    setOrganum([]);
    setError(null);
  };

  // --- Render ---
  return (
    <div className="app-shell" style={{ maxWidth: '1200px', margin: '0 auto', fontFamily: 'sans-serif' }}>
      
      <header style={{ padding: '20px', borderBottom: '1px solid #ddd' }}>
        <h1 style={{ margin: 0 }}>Medieval Organum Generator</h1>
        <p style={{ margin: '5px 0 0', color: '#666' }}>
          Phase 1 Counterpoint (c. 850–1100) • Styles: Enchiriadis, Micrologus, Ad Organum Faciendum
        </p>
      </header>

      {/* Controls */}
      <Controls 
        style={style} 
        setStyle={setStyle}
        onGenerate={handleGenerate}
        onPlay={handlePlay}
        onStop={handleStop}
        onClear={handleClear}
        onExport={handleExport}
        canGenerate={chant.length > 0}
        isPlaying={isPlaying}
      />

      {error && (
        <div style={{ background: '#fdd', color: '#900', padding: '10px', margin: '10px' }}>
          <strong>Generation Error:</strong> {error}
        </div>
      )}

      {/* Main Content Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '20px', padding: '20px' }}>
        
        {/* 1. Score Visualization */}
        <section>
          <ModernScore 
            chant={chant} 
            organum={organum} 
            selectedIndex={playbackIndex}
          />
          <GregorianScore 
            chant={chant} 
            organum={organum} 
            selectedIndex={playbackIndex}
          />
        </section>

        {/* 2. Input */}
        <section>
          <ChantInput onChantChange={handleChantChange} />
        </section>

        {/* 3. Analysis */}
        <section>
          <AnalysisPanel chant={chant} organum={organum} style={style} />
        </section>

      </div>
      
      <footer style={{ padding: '20px', textAlign: 'center', fontSize: '0.8rem', color: '#999' }}>
        Generated by Phase 1-9 Modular Architecture
      </footer>
    </div>
  );
};
